#!/bin/bash

pwd
echo Stage blog files 
git add --all

echo Commit blog files
git commit -m "update"

echo Push blog files
git push

cd output
pwd

echo Stage output files
git add --all

echo Commit output files
git commit -m "update"

echo Push output files
git push

cd ..
pwd

echo /// DONE! ///
