#!/bin/bash

cd ~/projects/blog
pwd

echo generate blog output files
pelican content -s publishconf.py

cd ../blog-output/output
pwd

echo Stage output files
git add --all

echo Commit output files
git commit -m "scheduled update"

echo Push output files
git push

cd ../../blog
pwd

echo Stage blog files 
git add --all

echo Commit blog files
git commit -m "scheduled update"

echo Push source files
git push

pwd


echo /// ALL DONE! ///

